### ISSUE TITLE
Improve code style and linting

### ISSUE THREAD

**Issue by kiurchv** [edenlabllc/nhs.admin.web#56]
- [x] Disable linters (#57) 
- [x] Add [prettier](https://github.com/prettier/prettier#pre-commit-hook) pre-commit hook (#57)
- [x] Replace deprecated [ghooks](https://github.com/ghooks-org/ghooks) with [husky](https://github.com/typicode/husky) (#57)
- [x] Setup eslint rules for prettier with [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) (#57)
- [x] Setup stylelint rules for prettier (currently there is not available suitable plugin for stylelint)
- [x] Ensure displayName presence for all components (#57)
- [x] Apply formatting to all codebase (#101)
- [x] Enable linters
